django_project/urls.py
from django.contrib import admin
from django.urls import path,include
from users import views as user_views
from django.contrib.auth import views as authentication_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('food/',include('food.urls')),
    path('register/',user_views.register,name='register'),
    path('login/',authentication_views.LoginView.as_view(template_name='users/login.html'),name='login'),
    path('logout/',authentication_views.LogoutView.as_view(template_name='users/logout.html'),name='logout'),
    path('profile/',user_views.profilepage,name='profile'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

food/urls.py
from . import views
from django.urls import path

app_name = 'food'

urlpatterns = [
    path('',views.IndexClassView.as_view(),name='index'),
    path('item/',views.item,name='item'),
    path('<int:pk>/',views.FoodDetail.as_view(),name='detail'),
    path('aboutus/',views.aboutus,name='aboutus'),
    path('add/',views.CreateItem.as_view(),name='create_item'),
    path('update/<int:item_id>/',views.update_item,name='update_item'),
    path('delete/<int:item_id>/',views.delete_item,name='delete_item'),
]

users/urls.py
from django import path

urlpattens = [
   
]

food/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
from django.urls import reverse
class Item(models.Model):

    def __str__(self):
        return self.item_name

    user_name = models.ForeignKey(User,on_delete=models.CASCADE,default=1)

    item_name = models.CharField(max_length=200)
    item_desc = models.CharField(max_length=200)
    item_price = models.IntegerField()
    item_img = models.CharField(max_length=500,default="https://img.freepik.com/free-icon/placeholder_318-855980.jpg")

    def get_absolute_url(self):
        return reverse('food:detail',kwargs={'pk':self.pk})

users/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    image  = models.ImageField(default='profilepic.jpg',upload_to='profile_pictures')
    location = models.CharField(max_length=100,default='India')

    def __str__(self):
        return self.user.username

food/forms.py
from django import forms
from .models import Item

class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['item_name','item_desc','item_price','item_img']

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class RegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username','email','password1','password2']

food/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .models import Item
# Create your views here.
from django.template import loader
from .forms import ItemForm
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView
def index(request):
    item_list = Item.objects.all()
   
    context ={
        'item_list':item_list,
    }
    return render(request,'food/index.html',context)    

class IndexClassView(ListView):
    model = Item;
    template_name = 'food/index.html'
    context_object_name = 'item_list'

def item(request):
    return HttpResponse('<h1>This is an item view </h1>')

def detail(request,item_id):
    items = Item.objects.get(pk=item_id)
    context = {
        'items':items,
    }
    return render(request,'food/detail.html',context)

class FoodDetail(DetailView):
    model = Item
    template_name = 'food/detail.html'

def aboutus(request):
    return render(request,'food/aboutus.html')

def create_item(request):
    form = ItemForm(request.POST or None)

    if form.is_valid():
        form.save()
        return redirect('food:index')
    return render(request,'food/item-form.html',{'form':form})

class CreateItem(CreateView):
    model = Item
    fields = ['item_name','item_desc','item_price','item_img']
    template_name = 'food/item-form.html'
    def form_valid(self,form):
        form.instance.user_name = self.request.user
        return super().form_valid(form)

def update_item(request, item_id):
    item = Item.objects.get(id=item_id)
    form = ItemForm(request.POST or None, instance=item)
    if form.is_valid():
        form.save()
        return redirect('food:index')
    return render(request, 'food/item-form.html', {'form': form, 'item': item})

def delete_item(request, item_id):
    item = Item.objects.get(id=item_id)
    if request.method == 'POST':
        item.delete()
        return redirect('food:index')
    return render(request, 'food/item-delete.html', {'item': item})

users/views.py
from django.shortcuts import render,redirect    
from django.contrib import messages
# Create your views here.
from .forms import RegisterForm
from django.contrib.auth.decorators import login_required


def register(request):
    if request.method=='POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request,f'Account created for {username}!')
            return redirect('login')
    else:
        form = RegisterForm()
    return render(request, 'users/register.html', {'form':form})

@login_required
def profilepage(request):
    return render(request, 'users/profile.html')

food/templates/food/aboutus.html
{% extends 'food/base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Food App</title>
    <link rel="stylesheet" href="{% static 'food/style.css' %}">
</head>
<body>
        {% block body %}
        <center>
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Iure, ducimus! <br>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fugiat rem suscipit at totam quod quos maiores, modi odit, accusamus molestiae neque repellendus. Voluptate, maxime error! <br>
            Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quos reprehenderit dicta odio perferendis quas quam inventore, quae est minus voluptate? <br>
            
        </center>
        {% endblock %}
</body>
</html>

food/templates/food/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Food App</title>
    <link rel="stylesheet" href="{% static 'food/style.css' %}" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9"
      crossorigin="anonymous"
    />
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm"
      crossorigin="anonymous"
    ></script>
    
    <style>
      body{
        background-color:black;
        color: white;
      }
      .btn {
 background-color: #00BFA6;
 padding: 14px 40px;
 color: #fff;
 text-transform: uppercase;
 letter-spacing: 2px;
 cursor: pointer;
 border-radius: 10px;
 border: 2px dashed #00BFA6;
 margin-top: 5px;
 margin-left: 85px;
 box-shadow: rgba(50, 50, 93, 0.25) 0px 2px 5px -1px, rgba(0, 0, 0, 0.3) 0px 1px 3px -1px;
 transition: .4s;
}

.btn span:last-child {
 display: none;
}

.btn:hover {
 transition: .4s;
 border: 2px dashed #00BFA6;
 background-color: #fff;
 color: #00BFA6;
}

.btn:active {
 background-color: #87dbd0;
}


    </style>
  </head>
  <body>
    <nav class="navbar navbar-dark bg-black navbar-expand-lg">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'food:index' %}">Food App</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
    
            <li class="nav-item">
              <a class="nav-link" href="{% url 'food:aboutus' %}">About us</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Pricing</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'food:create_item' %}">Add Items</a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'logout' %}">Logout</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'profile' %}"><strong>Account</strong></a>
            </li>
           {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'login' %}">Login</a>
            </li>
            {% endif %} 
            
          </ul>
        </div>
      </div>
    </nav>

    {% if messages %}
    {% for message in messages %}
      <div class="alert alert-{{message.tags}}">
        {{message}}
      </div>
    {% endfor %}
    {% endif %}

    {% block body %} {% endblock %}
  </body>
</html>

food/templates/food/detail.html
{% extends 'food/base.html' %} {% block body %}

<div class="container">
  <div class="row">
    <div class="col-md-6">
      <img src="{{object.item_img}}" class="card" alt="" />
    </div>
    <div class="col-md-6">
      <h1>{{object.item_name}}</h1>

      <h2>{{object.item_desc}}</h2>

      <h3>{{object.item_price}}₹</h3>

      <h1><a href="{% url 'food:update_item' object.id %}">Edit</a></h1>
      <h1><a href="{% url 'food:delete_item' object.id %}">Delete</a></h1>
    </div>
  </div>
</div>

{% endblock %}

food/templates/food/index.html
{% extends 'food/base.html' %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Food App</title>
    
    
  </head>
  <body>
    {% block body %}

    {% for items in item_list %}

    <div class="row">
        <div class="col-md-3">
            <img src="{{items.item_img}}" height="250px" width="350px" />
        </div>
            <div class="col-md-7">
                <h3>{{items.item_name}}</h3>
                <h4>{{items.item_desc}}</h4>
                <h5>{{items.item_price}}₹</h5>
                <h6>Posted by: {{ items.user_name}}</h6>
              </div>
                <div class="col-md-2">
                    <a href="{% url 'food:detail' items.id %}" class="btn btn-success">Details</a>
                </div>
            
        
    

    {% endfor %}

    {% endblock %}
  </body>
</html>

food/templates/food/item-delete.html
{% extends 'food/base.html' %}

{% block body %}
<form method="POST">
    {% csrf_token %}
    <label for="delete">Are you sure you want to go ahead?</label>
    <button class="btn" type="submit">Confirm</button>
</form>
{% endblock %}

food/templates/food/item-form.html
{% extends 'food/base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <div class="card">
                <div class="card-header bg-info">
                    <div class="card-title">
                        Add Item
                    </div>
                </div>
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                        {% for fields in form %}
                        <div class="form-group">
                            {{fields.name}} <br>
                            {{fields}}
                        </div>
                        {% endfor %}
                        <button class="btn" type="submit">Save</button>
                    </form>           
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/login.html
{% extends 'food/base.html' %}
{% block body %}

<div class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <div class="card">
                <div class="card-header bg-info">
                    <div class="card-title">
                        Login
                    </div>
                </div>
                <div class="card-body">
                    <form method="POST" >
                        {% csrf_token %}
                        {% for fields in form %}
                        <div class="form-group">
                            {{fields.name}}
                            {{fields}}
                        </div>
                        {% endfor %}
                        <button class="btn">Login</button>
                    </form>
                    <br>
                    <h3>Don't have an account?</h3>
<a href="{% url 'register' %}">Register</a>                    
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/logout.html
{% extends 'food/base.html' %}
{% block body %}
<h1>You have been logged out</h1>
{% endblock %}

users/templates/users/profile.html
{% extends 'food/base.html' %}
{% block body %}
<center>
<h1><u>Profile</u></h1>
<div class="profile-image">
    <img src ="{{user.profile.image.url}}" height="200px" width="200px">
</div>
<div class="user-name">
    Username: {{ user.username }}
</div>
<div class="email">
    Email: {{user.email  }}
</div>

{% if user.first_name != "" %}
<div class="uname">
    First Name: {{user.first_name}} <br>
    Last Name: {{user.last_name}}
</div>
{% endif %}

</center>
{% endblock %}

users/templates/users/register.html
{% extends 'food/base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <div class="card">
                <div class="card-header bg-info">
                    <div class="card-title">
                        Register
                    </div>
                </div>
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                        {% for field in form %}
                        <div class="form-group">
                            {{field.name}}
                            <br>
                            {{field}}
                        </div>
                        {% endfor %}
                        <button class="btn" type="submit">Register</button>
                    </form>
                    <h3>Already have an account?</h3>
<a href="{% url 'login' %}">Login</a>              
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}